### ISSUE TITLE
Supermarket

### ISSUE THREAD

**Issue by cmluciano** [irvingpop/supermarket-omnibus-cookbook#4]
Hey Irving, is there any chance that you can release this to the supermarket? For now I need to point my Berksfile to your github repo, which is fine for now.

Is this this going to be the de-facto method for installing supermarket or will there be another cookbook when supermarket is out of beta?

**Comment by irvingpop** [comment]
hey @cmluciano I will put "release to Supermarket" on my TODO list.  thanks!

I believe at some point the community Supermarket cookbook will get refactored to look a lot like this one, but I don't know when that's happening.

**Comment by irvingpop** [comment]
Done!  https://supermarket.chef.io/cookbooks/supermarket-omnibus-cookbook

**Comment by cmluciano** [comment]
👍 thanks!
